In [ ]:
def simple_model(input_text):
  # 긍정적인 핵심어 및 ngram, 가중치
  positive_keywords = {
        "최고": 3,
        "추천": 3,
        "진짜 좋다": 2.5,
        "대박": 3,
        "극찬": 3,
        "아늑": 2,
        "좋았습니다": 2,
        "맛집": 3,
        "진리": 3,
        "핫플": 2.5,
        "맛있": 2.5,
        "오고 싶다": 2.5,
        "너무 친절해서": 2,
        "기분 좋게": 1.5,
        "분위기도 좋고": 1.5,
        "진짜 ㄹㅇ": 2,
        "맛있어요": 2,
        "좋은": 1,
        "왔는데": 1,
        "정말": 1.5,
        "좋아요": 1
    }

    # 부정적인 핵심어 및 n-grams와 가중치
  negative_keywords = {
        "실망": 3,
        "아쉽다": 2.5,
        "그냥 그래": 2.5,
        "실망스러움": 3,
        "음식이 너무": 2,
        "너무 짜서": 1.5,
        "그냥 그랬어요": 2,
        "기대 이하였습니다": 2,
        "늦게 나오고": 1.5,
        "별로였어요": 2,
        "이렇게": 1,
        "너무": 1
    }


  # 키워드 길이에 따라 정렬(내림차순)
  sorted_positive_keywords = sorted(positive_keywords.keys(),  key=len, reverse=True)
  sorted_negative_keywords = sorted(negative_keywords.keys(),  key=len, reverse=True)

  positive_score = 0
  negative_score = 0

  # 긍정 키워드 점수 계산
  for key in  sorted_positive_keywords:
    if key in input_text:
      positive_score += positive_keywords[key]
      input_text = input_text.replace(key, "")
      # 중복 점수 방지하기 위해 키워드를 텍스트에서 제거

  # 부정 키워드 점수 계산
  for key in  sorted_negative_keywords:
    if key in input_text:
      negative_score += negative_keywords[key]
      input_text = input_text.replace(key, "")
      # 중복 점수 방지하기 위해 키워드를 텍스트에서 제거

  # 결과 반환
  if positive_score > negative_score:
    return 1
  else:
    return 0

In [ ]:
import urllib.request

urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/tykimos/tykimos.github.io/master/warehouse/dataset/tarr_train.txt",
    filename="tarr_train.txt",
)

('tarr_train.txt', <http.client.HTTPMessage at 0x7802f1c67fa0>)

In [ ]:
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
def classify_text(input_text):
   output = simple_model(input_text)
   return output

In [ ]:
# 파일을 데이터프레임으로 load

df = pd.read_csv('tarr_train.txt', delimiter='\t')
# delimiter='\t' (tab 기준으로 구분)
df.head()

   id                                      comment  label
0   1                  여기 음식은 언제 와도 실망시키지 않아요. 최고!      1
1   2  여기 라멘 진짜 ㄹㅇ 맛있어요. 국물이 진하고 면도 쫄깃해서 너무 좋았습니다.      1
2   3                     진짜 깔끔하고, 맛도 좋았어요. 추천합니다!      1
3   4                    왜 이렇게 유명한지 모르겠음ㅋㅋ ㄹㅈㄷ 맛없음      0
4   5      인생 타르트를 여기서 만났어요❤️ 달지 않고 고소해서 정말 추천합니다!      1

In [ ]:
actual_labels =[]
predicted_labels = []

for idx, row in df.iterrows():
  comment = row['comment']
  actual_label = row['label']
  predicted_label = classify_text(comment)

  actual_labels.append(actual_label)
  predicted_labels.append(predicted_label)

  print('comment: ', comment)
  print('actual_class: ', actual_label )
  print('predicted_class: ', predicted_label)
  print('--' * 100)

comment:  여기 음식은 언제 와도 실망시키지 않아요. 최고!
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  여기 라멘 진짜 ㄹㅇ 맛있어요. 국물이 진하고 면도 쫄깃해서 너무 좋았습니다.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  진짜 깔끔하고, 맛도 좋았어요. 추천합니다!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  왜 이렇게 유명한지 모르겠음ㅋㅋ ㄹㅈㄷ 맛없음
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  인생 타르트를 여기서 만났어요❤️ 달지 않고 고소해서 정말 추천합니다!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  메뉴 설명을 너무 친절하게 해주셔서 고르기 수월했어요.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  사진과 음식이 너무 달라서 실망했습니다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  주변에 추천하려고 사진도 많이 찍었어요. 좋아요!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  솔직히...? 맛이 그닥이에요. 리뷰랑 너무 다르네.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  진짜 개꿀맛..ㅠ 다른곳 안가.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  음식이 너무 늦게 나와서 기다리는 동안 답답했습니다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  음식도 맛있고, 가격도 합리적이에요. 다음에 또 오려구요.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  여기 리뷰보고 왔는데 ㅇㅈ? 실망스러움...
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  앞으로 여기 자주 올 것 같아요! 가성비 짱!ㅇㅈ? ㅋㅋ
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  마지막으로 온 게 언제였는지 모르겠는데, 여전히 인기 많네요!
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  ㅎㅎ 애들이랑 와서 잘 먹었어요. 아이들 메뉴도 맛있더라고요!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  주문한 음식이 전부 나오지 않아서 환불 요청했어요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  요새 여기가 핫플이라던데, 완전 공감!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  리뷰보고 왔는데 기대 이하였습니다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  안 와봤으면 큰일날뻔; 여기 김치찌개는 진리네 ㅎㅎ
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  이런 곳은 왜 유명해지지 않는 거죠? 숨은 맛집이네요!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  뭔가 빠진 느낌? 뭐가 문제인지는 모르겠는데, 그냥 별로였어요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  우리 할머니도 극찬하셨어요! 또 오고 싶다고 하시더라구요.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  음식도 늦게 나오고, 맛도 그닥... 실망이에요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  요새 패션에 맞게 리모델링도 하셨더라. 또 올게!
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  외관은 그냥 그랬는데, 내부가 너무 아늑하고 좋았습니다.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  사진보다 음식 portion이 좀 작은 거 아닌가요? 😐
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  ㅁㅊ! 여기 왜 이제야 알게됐지? 대박 맛집이네!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  이게 뭐야? ㅁㅊ라고 이렇게 매운 거라도 미리 얘기 좀 해줘야지. 입 안에서 불 키는 줄...
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  OMG! 이런 맛집을 지금서야 발견하다니ㅋㅋ 대박❤️
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  전체적으로 괜찮았지만, 음악 소리가 너무 커서 조금 시끄러웠습니다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  진짜 미친듯이 맛있어서 놀랐네요. ㄷㄷ... 여기는 천국이냐?
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  이전에 왔을 때보다 서비스가 많이 떨어진 것 같아요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  이렇게 좋은 곳이 있었는데, 왜 이제야 알았을까요? 다들 방문해보세요!
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  방문하려고 했는데, 문을 닫았더라고요. 영업 시간을 좀 더 정확히 표시해주셨으면 좋겠어요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  가격 대비 음식의 양이 너무 적었어요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  음식이 너무 짜서 물을 계속 마셨습니다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  솔직히 맛은 그냥 그랬어요. 하지만 분위기는 좋았습니다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  요기 돈까스 진짜 맛있어요. 돈까스 좋아하시는 분들 꼭 와보세요!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  처음 와봤는데, 분위기도 좋고 음식도 만족스러워서 잘 먹었어요.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  여기는 꼭 한 번 방문해봐야 해요! 너무 만족했습니다.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  우리 아들이랑 왔는데, 아이 메뉴도 좋더라고요.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  아니, 메뉴 주문한지 40분 넘었는데 안 나와요?
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  전 직원분들의 친절함에 감동 받았습니다. 음식도 무척 훌륭했어요.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  청결도가 좀... 특히 화장실이 좀... ㅠㅠ
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  괜찮았어요.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  처음 와보는데, 전통과 현대가 조화로운 곳이네요. 다음에 또 방문하려고요.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  직원들이 너무 친절해서 기분 좋게 식사했습니다. 감사합니다.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  직원들의 태도가 너무 불친절해서 기분이 안 좋았어요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  주차공간이 너무 협소해서 불편했습니다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  좀 너무 기대하고 왔나봐요... 뭐 이런 것도 있지 뭐 😑
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  최악의 응대... 여기 다시는 안 갈래요. 😡
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  진짜 대박! 여기 인테리어 너무 이쁘고, 음식도 인스타갬성 폭발!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  불친절해서 기분 나빴어. 주문하려는데 계속 대화하고 있더라구요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  바다가 보이는 자리에서 식사하는 게 정말 로맨틱했어요. 분위기 최고에요!
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  식사 중에 바퀴벌레가 나와서 기분이 엄청 나빴습니다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  나중에 가게 될 걸 알았으면 아예 안 올 걸 그랬네. 재료가 신선하지 않아 보였어요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  처음부터 끝까지 서비스가 너무 좋았습니다. 직원들도 친절하시고, 음식은 말할 것도 없이 너무 맛있었어요. 특히 메인디쉬는 인상 깊었네요.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  나한테는 좀 너무 달았어.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  친구 추천으로 왔는데, 정말 잘 선택한 것 같아요. 👏
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  직원분이 계속 쳐다보면서 서비스 해주셔서 좀 불편했어요. 알바생 훈련이 필요해보여요.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  ㄱㅊ... 특별히 기대 안 했는데 꽤 괜찮았어.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  전통적인 맛 그대로, 우리 할머니 생각나게 하는 음식이었습니다. 감사합니다.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  단체로 왔는데, 모두다 만족하며 나갔어요.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  그냥 그랬다.
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  인테리어가 너무 이쁘더라고요. 사진 찍기 좋아요!
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  전 주차 때문에 여기 올 거면 차 대지 말라고 하고 싶네요. 주차장이 너무 협소하더라고요...
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  옛날 할머니집에서 먹던 그 맛이 났어요. 너무 행복한 식사였습니다.
actual_class:  1
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  ㄴㅇㄱ... 여기서 이런 일을 겪을 줄이야...
actual_class:  0
predicted_class:  0
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  저녁 데이트로 딱 좋은 곳이네요! 분위기도 좋고, 음식도 훌륭해요.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  한국 전통 음식을 찾으시는 분들에게 추천합니다! 정감있고 맛도 좋아요.
actual_class:  1
predicted_class:  1
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
comment:  젊은 사람들이 좋아할만한 분위기에다가, 메뉴 구성도 신선하네요! 잘 먹었습니다!
actual_class:  1
predicted_class:  0

In [ ]:
# 정확도 계산
accuracy = accuracy_score(actual_labels, predicted_labels)
# y_real, y_pred 비교 (cost 줄이는 게 우리의 목표)

print(f"Accuracy: {accuracy*100:.2f}%")

print(set(actual_labels))
print(set(predicted_labels))

# Confusion matrix 계산
cm = confusion_matrix(actual_labels, predicted_labels, labels=[1, 0])
# Confusion matrix 표현
print("\nConfusion Matrix:")
print("         Predicted:")
print("         긍정    부정")
print("Actual")
print("긍정      {:<5}  {:<5}".format(cm[0][0], cm[0][1]))
print("부정      {:<5}  {:<5}".format(cm[1][0], cm[1][1]))

Accuracy: 76.33%
{0, 1}
{0, 1}

Confusion Matrix:
         Predicted:
         긍정    부정
Actual
긍정      100    62
부정      9      129

In [ ]:
urllib.request.urlretrieve(
    "https://raw.githubusercontent.com/tykimos/tykimos.github.io/master/warehouse/dataset/tarr_sample_submit.txt",
    filename="tarr_sample_submit.txt",
)

('tarr_sample_submit.txt', <http.client.HTTPMessage at 0x7802b67faa10>)

In [ ]:
df_submit = pd.read_csv('tarr_sample_submit.txt', delimiter='\t')
df_submit

     id                                            comment  label
0     1                      완전 내 스타일이에요! 가격도 적당하고 위치도 좋고👌      0
1     2                            맛있긴 한데 양이 너무 적어서 좀... ㅠ      0
2     3                       완전 내 스타일이에요 ㅠㅠ 여기 매장 분위기도 이쁨      0
3     4       한국의 전통 음식을 잘 표현한 것 같아요. 향토음식의 정취가 느껴져 좋았습니다.      0
4     5                        서빙하는 분이 좀 불친절해서 기분이 좀 그랬어요.      0
..  ...                                                ...    ...
95   96                     가성비 최고! 이 가격에 이런 맛은 정말 만족스러워요.      0
96   97                         와... 여기김치... 말도안됨... ㅁㅊ...      0
97   98                       주문한 지 40분 넘게 기다려서 음식 나왔네요...      0
98   99                      아이들이랑 왔는데, 키즈 메뉴도 생각보다 맛있었어요!      0
99  100  오랜만에 외식을 했는데, 이런 결과를 보게 될 줄은 몰랐네요. 음식도 별로고, 서비...      0

[100 rows x 3 columns]

In [ ]:
predicted_labels = []

# 각 row 를 순회하면서 코멘트를 분류
for index, row in df_submit.iterrows():
  comment = row['comment']
  predicted_label = classify_text(comment)
  predicted_labels.append(predicted_label)

# 예측된 레이블 >> 데이터프레임에 추가
df_submit['label'] = predicted_labels

# 결과를 저장
df_submit

     id                                            comment  label
0     1                      완전 내 스타일이에요! 가격도 적당하고 위치도 좋고👌      0
1     2                            맛있긴 한데 양이 너무 적어서 좀... ㅠ      1
2     3                       완전 내 스타일이에요 ㅠㅠ 여기 매장 분위기도 이쁨      0
3     4       한국의 전통 음식을 잘 표현한 것 같아요. 향토음식의 정취가 느껴져 좋았습니다.      1
4     5                        서빙하는 분이 좀 불친절해서 기분이 좀 그랬어요.      0
..  ...                                                ...    ...
95   96                     가성비 최고! 이 가격에 이런 맛은 정말 만족스러워요.      1
96   97                         와... 여기김치... 말도안됨... ㅁㅊ...      0
97   98                       주문한 지 40분 넘게 기다려서 음식 나왔네요...      0
98   99                      아이들이랑 왔는데, 키즈 메뉴도 생각보다 맛있었어요!      1
99  100  오랜만에 외식을 했는데, 이런 결과를 보게 될 줄은 몰랐네요. 음식도 별로고, 서비...      0

[100 rows x 3 columns]

In [ ]:
df_submit[['id','comment','label']].to_csv('tarr_my_submit.txt', sep='\t', index=False)

In [ ]:
df_submit.head()

   id                                       comment  label
0   1                 완전 내 스타일이에요! 가격도 적당하고 위치도 좋고👌      0
1   2                       맛있긴 한데 양이 너무 적어서 좀... ㅠ      1
2   3                  완전 내 스타일이에요 ㅠㅠ 여기 매장 분위기도 이쁨      0
3   4  한국의 전통 음식을 잘 표현한 것 같아요. 향토음식의 정취가 느껴져 좋았습니다.      1
4   5                   서빙하는 분이 좀 불친절해서 기분이 좀 그랬어요.      0